apiVersion: v1
kind: Namespace
metadata:
    name: experiments
---
# ------------------------------------------------------------
# ConfigMap приложения experiments-app
# ------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
    name: experiments-config
    namespace: experiments

data:
    TZ: Europe/Moscow
    BACKEND_APP_BASE_IS_PROD: "true"
    BACKEND_APP_BASE_USE_FX_LOGGER: "false"
    BACKEND_APP_BASE_USE_LOGGER: "true"
    BACKEND_APP_BASE_LOG_SQL_QUERIES: "false"
    BACKEND_APP_BASE_LOG_HTTP: "true"
    TEMPORAL_WORKER_APP_BASE_IS_PROD: "true"
    TEMPORAL_WORKER_APP_BASE_USE_FX_LOGGER: "false"
    TEMPORAL_WORKER_APP_BASE_USE_LOGGER: "true"
    TEMPORAL_WORKER_APP_BASE_LOG_SQL_QUERIES: "false"
    TEMPORAL_HOST: "temporal-frontend.neurochar.svc.cluster.local:7233"
    TEMPORAL_NAMESPACE: "neurochar"
    TEMPORAL_WORKER_APP_ML_WORKER_SERVICE: "ml-worker-nodeport.ns.svc.cluster.local:50051"
    TEMPORAL_WORKER_APP_ML_WORKER_READINESS: "http://ml-worker-nodeport.ns.svc.cluster.local:8000/ready"
    TEMPORAL_WORKER_APP_ML_WORKER_FALLBACK_SERVICE: "ml-worker-cpu-nodeport.ns.svc.cluster.local:50051"
    STORAGE_S3_ENDPOINT: "https://storage.yandexcloud.net"
    STORAGE_S3_REGION: "ru-central1"
    STORAGE_S3_URL: "https://storage.yandexcloud.net"
    STORAGE_S3_URL_IS_HOST: "true"
    STORAGE_S3_URL_HOST_PREFIX: "https://"
    STORAGE_S3_URL_HOST_POSTFIX: ".storage.yandexcloud.net"

---
# ------------------------------------------------------------
# Deployment приложения experiments-app
# ------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
    name: experiments-app-deployment
    namespace: experiments

spec:
    replicas: 1

    selector:
        matchLabels:
            app: experiments-app

    template:
        metadata:
            labels:
                app: experiments-app

        spec:
            containers:
                - name: experiments-app-service
                  image: cr.yandex/crpgiggf30987ecj5lp4/experiments/service:latest
                  imagePullPolicy: Always

                  ports:
                      - containerPort: 8080

                  envFrom:
                      - configMapRef:
                            name: experiments-config
                      - secretRef:
                            name: experiments-app-secret

                - name: experiments-app-worker
                  image: cr.yandex/crpgiggf30987ecj5lp4/experiments/temporal-worker:latest
                  imagePullPolicy: Always

                  envFrom:
                      - configMapRef:
                            name: experiments-config
                      - secretRef:
                            name: experiments-app-secret

---
# ------------------------------------------------------------
# Service для приложения experiments-app
# ------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
    name: experiments-app-service
    namespace: experiments
    labels:
        app: experiments-app

spec:
    type: NodePort
    selector:
        app: experiments-app
    ports:
        - name: http
          port: 8080
          targetPort: 8080
          nodePort: 31800
